// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWexUgyybacbPp-Vsp1ELTM3J50s_uGo',
    appId: '1:375960945923:web:b5e935bf34a05c70bd1536',
    messagingSenderId: '375960945923',
    projectId: 'loginapp-a64e5',
    authDomain: 'loginapp-a64e5.firebaseapp.com',
    storageBucket: 'loginapp-a64e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1IeICeg_ndOv4tqd7XcBmxwTHG8sPslk',
    appId: '1:375960945923:android:6d8cc84f399ca8d4bd1536',
    messagingSenderId: '375960945923',
    projectId: 'loginapp-a64e5',
    storageBucket: 'loginapp-a64e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TAQswsEaYl_wwkDwxNQCk2JVW32cL6Y',
    appId: '1:375960945923:ios:403b509ade70a351bd1536',
    messagingSenderId: '375960945923',
    projectId: 'loginapp-a64e5',
    storageBucket: 'loginapp-a64e5.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4TAQswsEaYl_wwkDwxNQCk2JVW32cL6Y',
    appId: '1:375960945923:ios:b5b631b91adf2b73bd1536',
    messagingSenderId: '375960945923',
    projectId: 'loginapp-a64e5',
    storageBucket: 'loginapp-a64e5.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
